"""Migração Inicial

Revision ID: fe95bb4c22ed
Revises: 
Create Date: 2024-09-06 14:48:53.688716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe95bb4c22ed'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('id_categoria', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=True),
    sa.Column('descricao', sa.String(length=200), nullable=True),
    sa.Column('codigo', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id_categoria')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('categorias')
    # ### end Alembic commands ###
